source tracks('TRACK':string,'DATE':int,'RATING':int,'ALBUM':string).
source albums('ALBUM':string,'QUANTITY':int).
view tracks1('TRACK':string,'DATE':int,'RATING':int,'ALBUM':string,'QUANTITY':int).

% constraints:

⊥ :- tracks1(T,D,R,A,U1), tracks1(U2,U3,U4,A,Q), not tracks1(T,D,R,A,Q).

% view definition:
tracks1(T,D,R,A,Q) :- tracks(T,D,R,A), albums(A,Q).

% caculate delta relation of tracks for the modification in the view
+tracks(TRACK,DATE,RATING,ALBUM) :- tracks1(TRACK,DATE,RATING,ALBUM,U1), not tracks(TRACK,DATE,RATING,ALBUM).
-tracks(TRACK,DATE,RATING,ALBUM) :- tracks(TRACK,DATE,RATING,ALBUM),not tracks1(TRACK,DATE,RATING,ALBUM,U1), albums(ALBUM,U2).
-tracks(TRACK,DATE,RATING,ALBUM) :- tracks(TRACK,DATE,RATING,ALBUM),not tracks1(TRACK,DATE,RATING,ALBUM,U1), tracks1(U2,U3,U4,ALBUM,U5).

% caculate delta relation of albums for the modification in the view
+albums(ALBUM, QUANTITY) :- tracks1(U1,U2,U3,ALBUM,QUANTITY), not albums(ALBUM,QUANTITY).
-albums(ALBUM, QUANTITY) :- albums(ALBUM,QUANTITY), not tracks1(U1,U2,U3,ALBUM,QUANTITY), tracks(TRACK,DATE,RATING,ALBUM), not -tracks(TRACK,DATE,RATING,ALBUM).
-albums(ALBUM, QUANTITY) :- albums(ALBUM,QUANTITY), not tracks1(U1,U2,U3,ALBUM,QUANTITY), +tracks(TRACK,DATE,RATING,ALBUM), not -tracks(TRACK,DATE,RATING,ALBUM).
-albums(ALBUM, QUANTITY) :- albums(ALBUM,QUANTITY), not tracks1(U1,U2,U3,ALBUM,QUANTITY), tracks1(U4,U5,U6,ALBUM,U7), not -tracks(U8,U9,U10,ALBUM).
